bigskysoftware/_hyperscript

- www/index.md
> Fix syntax error in example code

- src/_hyperscript.js
To make the public API easier to find and hence easier to understand.
> Move _hyperscript definition to top

- src/_hyperscript.js
- test/commands/js.js
- test/features/js.js
- test/index.html
This PR contains functionality to embed JS into \_hyperscript in two ways:
- At the top level, among defs and workers
- Inline, among commands
```hyperscript
js
function foo() {
// some garbage js
}
// functions are private by default and can be exposed to
// the global scope by returning them in an object:
return { foo }
end
def foo()
set x to 10
js(x)
// IIFE
return x + someJavscriptFunction()
end
log it
end
```
As part of this, the lexer generates `"RESERVED"` tokens for the characters `` ` ^ ``, since these can occur in JavaScript. These tokens won't be recognized by the parser outside of JS blocks.
> Embedded JS

- src/worker.js
Right now, the worker functionality relies on marker comments to extract the code of the worker function. Minification breaks this as it removes comments. With this PR, workers will function properly in the minified build.
> Make workers work when minified

- www/features/on.md
Just a tiny typo I spotted while reading the docs
> Typo: hanlder -> handler

- src/lib/core.js
I found this from a static analysis of the code base.  I'm not positive that it's the right thing to do, so I'm separating it out into its own PR.  Sorry to be pedantic.
This looks like a function is being passed in to a place that accepts a string value.  Adding a function dereference so that it matches all the other statements this block.
I'm not sure where it's used, or how to add a test for this, but let me know and I'm happy to add test cases.
> BUGFIX: Missing function call 

- src/lib/core.js
- test/expressions/objectLiteral.js
The following now work as expected: 
- `{foo-bar: "baz"}`
- `{[foo.bar()]: "baz"}`
> Object literal improvements

- src/lib/core.js
- test/commands/set.js
The following now works: 
```hyperscript
set obj to { foo: 1 }
set { bar: 2, baz: 3 } on obj
```
> `set` cmd: Set many properties at once using an object literal

- src/lib/web.js
- test/commands/add.js
The following now works:
```hyperscript
add { color: 'red', 'font-size': calcFontSize() } to #elt
```
(the quotes around `'font-size'` will be unnecessary with #61)
> add cmd: Add css properties with object literal

- src/lib/web.js
I probably should've opened an issue for this first, but the `take` command was failing for me with the error `e.classList is undefined` when I used it without a target. This PR fixes that.
The code that was breaking: 
```hyperscript
on click
with closest <li/> to target
take .active -- this was breaking
...
end
```
> Fix `take` command

- src/lib/core.js
- src/lib/web.js
- test/expressions/asExpression.js
I've updated this so that it will work with a NodeList (and not just a single DOM Node).  This makes `as Values` work with query selectors like this:
```html
<div _="on click put <input.include/> as Values into my.customData">
<input class="include" name="firstName" value="John"><br>
<input class="include" name="lastName" value="Connor"><br>
<input class="include" name="areaCode" value="213">
<input class="dont-include" name="phone" value="555-1212">
</div>
```
In the case above, only the inputs marked "include" will show up in the customData struct.  The "dont-include" element is ignored.
One notable side-effect of this PR is that `forEach` has been included in hyperscript's public API.
> Updates to `as Values`

- src/lib/web.js
- test/expressions/asExpression.js
- www/expressions/as.md
This PR adds an "as HTML" converter to the web.js library.  "As HTML" converts different objects as follows: 
* HTML Elements => the element's `outerHTML`
* NodeLists => a concatenated string of each element's `.outerHTML`
* Other Arrays => a concatenated string of each element (with no comma delimiters)
* Anything else => `.toString()` representation
Includes tests and documentation
> FEATURE "as HTML"

- src/lib/core.js
- test/expressions/arrayIndex.js
- test/index.html
This PR adds the area range notation that was requested on Discord.  Here are the formats supported:
```
set myVar to [0,1,2,3,4,5,6,7,8,9]
myVar[1] => 1
myVar[..4] => [0,1,2,3,4]
myVar[5..] => [5,6,7,8,9]
myVar[3..6] => [3,4,5,6]
```
This feature set *works* with one enormous caveat.  It seems like parsing numbers can break if they are immediately next to the ellipsis operator.  Without digging deeper, I suspect it may be because numbers can end with a period, which throws off the parser.  
To demonstrate this, I have made two sets of tests -- one that pass because an extra whitespace has been added into the range definitions like this `myVar[3 .. 6]`, and another that fails because the numbers are bunched together.
**Before we can merge this change** I'll need someone with more parsing …
> FEATURE: Array Range Notation

- src/lib/core.js
- src/lib/types.js
This PR includes more progress on the JSDoc project.  There are still plenty of "compiler warnings" due to incompletely defined types, but it's coming together pretty nicely.  As always, all automated tests are passing.
These changes are *mostly* documentation only, but there are a few minor formatting/style changes as well, included because they were making the Typescript validator complain.  For instance, it doesn't like when we overwrite a variable of one type with a new value of a different type.  This is fixed by choosing a new variable name for the other type.  I also removed a small number of redundant "else" statements that appear after a "return" -- this shortens the code by a tiny amount, and reduces the overall code complexity.  Hopefully this is considered a win :)
> JSDoc Progress

- www/playground/drag.html
use pageX,Y instead of clientX,Y. The reason this did not cause issues in hdb is that it's position: fixed.
> Fix drag.html: Element jumps above cursor if page scrolled down

- src/lib/core.js
- test/commands/increment.js
- test/index.html
This PR adds increment / decrement commands to hyperscript.
* It allows `increment <variable> by <amount>` so that you 
* The amount defaults to 1, so that `increment <variable>` just adds one to the value.
* It parses variables as a floating point number, so that `increment <variable that's 5.2> by 1.3` correctly sets the value to 6.5
* It uses `makeSetter()` function, so it works with properties, attributes, and object references
* If a value is not present, it assumes zero, and increments/decrements from there.
> Increment / Decrement commands

- src/lib/web.js
- test/expressions/asExpression.js
This conversion converts strings, elements and arrays thereof into DocumentFragment.
> "as Fragment": Conversion to parse HTML

- www/docs.md
Currently the Markdown code formatting syntax is missing from the Exceptions example in docs.md, so the example is being filtered out as a literal script tag:
> Fix code syntax for Exceptions example in docs.md

- src/lib/core.js
- test/commands/fetch.js
If the `as ...` clause is not text, response of json, it will be parsed as a [conversion](https://dev.hyperscript.org/expressions/as/).
> Allow fetch to use custom conversions

- www/commands/fetch.md
The docs are not up todate to the syntax of fetch: you'll have to use the conversion `as response` to get the response object. The docs state `as request`.
> syntax: changed request to response

- www/commands/go.md
Example code doesn't work as it was missing a 'url' inside it. Small fix in docs.
> fix missing 'url' in example code of go command docs

- src/lib/core.js
- test/commands/fetch.js
- test/index.html
- www/commands/fetch.md
This enables the user to globally access and modify the parameters of fetch. The command parameters are passed to the `event.detail` object which can be modified in the handler. The modified values are passed to the [fetch-API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).
This is especially useful for backends which require certain custom headers i.e. django's X-CSRFToken. Instead of setting this on every fetch command, the user can now use the event handler to do this.
> Add event to modify fetch parameters just before sending the fetch request.

- test/commands/append.js
This failing test shows that there is a bug when appending a string to a DOM element.
> Added failing append test

- www/reference.md
This just bit me when I was looking at the docs, couldn't figure out why it wasn't getting parsed.
> (docs) fetch json not JSON

- www/commands/fetch.md
Per discord discussion, updating the reference page for `fetch` with an example of using template literal strings to dynamically generate URLs for the fetch command.
> Update Reference Page for `fetch` Command

- src/lib/core.js
- www/_includes/layout.njk
When including external _hs files like so:
```html
<script type="text/hyperscript" src="one._hs"></script> 
<script type="text/hyperscript" src="two._hs"></script> 
<script src="dist/_hyperscript_w9y.min.js"></script>
```
the current behaviour of including these scripts is to fetch the scripts in a promise and execute (`_runtime.evaluate`) the code as it comes in from fetch. However, when one file is bigger or due to random network effects, this order of execution is currently random. When your second _hs file depends on methods or something from the first _hs file, this can sometimes lead to errors.
In this pull request propose changing this exeuction behavior to follow the order in which the scripts are included in the page, just like JS files would be executed.
In order to do this, I …
> process text/hyperscript <script> tags sequentially

- src/lib/plugin/socket.js
- test/features/socket.js
- test/index.html
- test/sockets/scratch.html
- www/features/socket.md
Hyperscript should complete WebSocket URLs in the socket feature the same way htmx does (see PR [#382](https://github.com/bigskysoftware/htmx/pull/382) by @srkunze):
- If no host and port is provided, use the current one
- For http use ws, for https use wss
(See https://github.com/bigskysoftware/_hyperscript/issues/221)
> Complete URLs in socket feature

- www/docs.md
Correction: The documentation said 'before' but meant 'after'
> Fixed typo on line 1323 - from 'before' to 'after'

- package-lock.json
- package.json
@dz4k requested this PR, saying he thought he already removed this dependency.
This dependency caused errors on `npm install` due to use of deprecated `node-sass`
> remove unused devDependency eleventy-plugin-sass

- www/docs.md
- www/expressions/no.md
Small additions to the current documentation clarifying the behavior of the `no` operator.
> Improve documentation about checking undefined and empty strings/arrays

- www/comparison.md
Perhaps illustrating the problem firsthand 😄 , the ID of the div and that of the CSS don't match. So, no transition is occurring, and the event `transitionend` never fires. The element snaps its opacity onclick, but is never removed.
Change should make the example functional again.
> fix(docs): Incorrect target on vanilla-remove-me example

- src/lib/core.js
Every so often, hyperscript crashes with the error
```
_hyperscript_w9y-0.9.4.min.js?v=c6fdfd9889:1 
Uncaught (in promise) TypeError: Invalid value used as weak map key
at WeakMap.set (<anonymous>)
at w (_hyperscript_w9y-0.9.4.min.js?v=c6fdfd9889:1:15847)
at evaluate (_hyperscript_w9y-0.9.4.min.js?v=c6fdfd9889:1:18308)
at Array.forEach (<anonymous>)
at _hyperscript_w9y-0.9.4.min.js?v=c6fdfd9889:1:69188
// since this is minified, the lines are kind of messed up, however:
// - WeakMap.set happens in getHyperscriptFeatures on line 1699 of core.js
// - getHyperscriptFeatures  is called in line 1857 of evaluate (core.js)
// - evaluate is called as _runtime.evaluate in line 5690 after downloading external ._hs scripts (core.js)
// - elt should in this case be <body> but is (very rarely) null …
```
> fix rare WeakMap error if 'elt' is null

- www/expressions/me.md
Fix #200 by removing references to unimplemented token 'myself' from documentation.
> Remove reference to nonexistent token 'myself' from docs

- www/docs.md
A little  typo on:
> **put content after element**
> Puts the content in front of the element, using Element.after
Changed to:
> **put content after element**
> Puts the content after the element, using Element.after
> typo on put-after syntax

- www/features/on.md
though `queued last` is a bit more natural. Perhaps
> on: typo with queue

- www/commands/fetch.md
The conversion specified in the docs for the `fetch` command is wrong.
> Fix conversion typo in fetch docs (close #241)

- src/lib/core.js
- src/lib/plugin/template.js
- src/lib/web.js
- test/core/scoping.js
- test/expressions/asExpression.js
- test/expressions/attributeRef.js
- test/expressions/comparisonOperator.js
- test/expressions/positionalExpression.js
- test/expressions/possessiveExpression.js
- test/expressions/propertyAccess.js
- test/expressions/queryRef.js
- test/expressions/strings.js
- test/expressions/symbol.js
- test/templates/templates.js
Currently local variables are stored directly on `context`. This PR moves those values into a new object, `context.locals`.
In the current strategy the direct assignment of local variables to `context` aligns the usage with changing normal JS object properties, e.g. Element properties, style properties. So these two examples currently work the same way:
`set x to 5` is equivalent to `context['x'] = 5`
`set body's innerHTML to 'hello'` is equivalent `body['innerHTML'] = 'hello'`.
This PR changes the implementation of the first example, and only the first one, to be equivalent to `context.locals['x'] = 5`.
To differentiate the context from other objects, this PR adds `context.meta.__hs_context = true` to each context.
Also changes template plugin to add an entry to `context.meta` instead of …
> Isolate local variables into `context.locals`

- README.md
- src/_hyperscript.js
- test/core/parser.js
- test/core/tokenizer.js
- www/docs.md
- www/index.md
- www/posts/2022-07-12-hyperscript-0.9.6-is-released.md
* Introduces more flexible comment types (`---` `//` `/* */`)
* Less friction for adoption of Hyperscript for Javascript developers and teams. Bring more people in!
* Enables far more gradual migrations.
* Migrate individual lines of code from javascript to hyperscript "in-place". Shared comment style is highly underrated for this.
* Multi-line comments will provide many other major wins to Hyperscript:
* Easier debugging by allowing you to "block out" problematic code.
* Less syntax wordiness when writing documentation comments.
* Refactor: `charAfterThat()` ➡ `nextCharAt(number)`
* Optionally specify the number of chars to look ahead. 
* Better naming consistency with `nextChar()`
Adds 3 new comment types: 
* `---`
* Allow more than two dashes to be a comment without clashing with [CSS …
> Improved comment ergonomics.

- www/docs.md
Directly addresses:
* https://news.ycombinator.com/item?id=32085561
Greatly improves the existing "Inline Javascript" section, puts all the applicable information in one place.
> Docs: Better Javascript to Hyperscript migration docs.

- www/docs.md
There was not mention of it on the docs, except on the Security section (without making it clear that they were alternatives to `_`).
> Mention script and data-script as alternative attributes

- src/_hyperscript.js
- test/core/tokenizer.js
- test/expressions/numbers.js
This commit allows native consumption of numbers written in scientific notation, e.g. 1e6 without using the workaround of `"1e6" as Float`.
> Resolves #333 by implementing support for scientific notation

- package.json
Simply adds `dist/` to `files` in `package.json`.
I’m not familiar with your release process so I’m not sure if this messes anything else up. I’m assuming the files under the git repo under _dist/_ are always the latest builds.
Fixes #370
> Add dist folder to package so it’s included in an npm install (fixes #370)

- test/features/behavior.js
The browser console, when running this failing test says `'element's bar' is null` along with the hypertrace.
Suprisingly, the following (which is almost the same) runs correctly on the playground:
```
<script type="text/hyperscript">
behavior Behave
init
set element's foo to 0
set element's bar to {}
end
on click
increment element's foo
set element's bar["count"] to element's foo
put element's bar["count"] at the end of #output
end
end
</script>
<button id="elem" _="install Behave init put 'foo' at the end of  #output">CLICK ME</button>
<hr/>
<div id="output"></div>
```
(as of today, the current release seems to be 0.9.5, which I've confirmed to have the issue)
> Add failing test for variables inside behaviors

- src/_hyperscript.js
- test/expressions/classRef.js
Now Tailwind classes like `-transform-x-5` work as expected.
Credit goes to YesOperator on the Discord.
> Added support for classes with leading hyphens

- www/commands/pseudo-commands.md
- www/docs.md
- www/expressions.md
- www/expressions/of.md
Some examples in the docs were showing how to refresh the current web page using the `window.location.refresh` method. However, the actual method is `reload` (ref: https://developer.mozilla.org/fr/docs/Web/API/Location/reload).
This PR just fixes them accordingly 🙂 I've left out `docs_old.md`, as it seems to be a backup file, but I can apply the change there if needed too.
> Docs: fix window.location.reload examples

- www/cookbook/90-filter-table-rows.md
Should use the [possessive “its”](https://hyperscript.org/expressions/possessive/), even if the syntax seems to allow it to work.
> fix(cookbook): English syntax

- www/_includes/layout.njk
Unfortunately `async` and `defer` is causing a race.
The result is:
* page highlighters randomly break or only partially highlight on some visits.
* hyperscript.js breaks randomly...
Removed the `async` and `defer`.
> [Website] Fix race condition where highlighters only load sometimes.

- www/expressions/closest.md
Fix a minor error on documentation of `closest`.
#432
> Fix doc on cloesest

- src/_hyperscript.js
- test/commands/take.js
- www/commands/take.md
Primary use case is manipulation of aria-properties (`aria-selected`, `aria-current`), but obviously can be used with any attribute for any purpose. Inspired by discussion on accessibility in discord/twitter and my own experience implementing drag-n-drop.
Comments on syntax are welcome
> Implement attribute support for `take` command

- src/socket.js
When I was experimenting with the example code from the documentation, `undefined` would always be logged to the console. (I could confirm with Chrome's developer tools that the messages were indeed coming through)
```hyperscript
socket MySocket ws://myserver.com/example
on message as json
log message
end
```
Additionally, if I added the command
```hyperscript
log result
```
it actually logs the message received from the socket.
I did some digging around to try and understand what was going on behind the scenes, and I think adding 'message' to the local context is the correct way forward. Hopefully this is correct!
> Fixed the context where the socket's 'message' symbol is located

- www/docs.md
* removing errant backtick
* fixed minor docs typo for CSS unit literal example
> removing errant backtick * CSS unit

- package.json
Currently typescript users for example `AstroJS` importing hyperscript is complicated. The following will throw an error about missing types. 
```ts
import hyperscript from 'hyperscript.org';
hyperscript.browserInit();
```
As we currently see in the repository there already exists an empty type definition file `dist/_hyperscript.d.ts`  So this PR only introduces an additional script command and the path to generated typings
closes #353
> generate typescript typings on the build time

- src/_hyperscript.js
- test/core/tokenizer.js
I recently found myself needing a hex escape and discovered that _hyperscript doesn't interpret those, forcing me to use something like
```
js return '\x41' end
log it
```
The implementation is trivial and could easily be extended to accomodate full unicode escapes.
```js
// before PR
log '\x41' // x41
// after PR
log '\x41' // A
```
> JS-style hex escapes in strings

- www/index.md
Unless the example is intentionally avoiding magenta, the random hue can go up to 360.
https://developer.mozilla.org/en-US/docs/Web/CSS/hue
> example hue up to 360

- www/docs.md
- www/features/on.md
- www/posts/2021-03-06-hyperscript-0.0.5-is-released.md
- There's no event `touchbegin`, so replacing it in the examples with [touchstart](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event)
- Fixed up some deadlinks.
> Docs: Fix typos and broken links

- src/_hyperscript.js
Fixes #559 .
If you're using Hyperscript on nodes within a shadow DOM (don't ask, it's  transitional), events won't pass the shadow DOM boundary by default. Adding `composed: true` lets them pass. 
I ran into this issue myself, and it also appears to be the same root cause as #559 .
> Add `composed: true` to triggered events

- www/reference.md
> fix typo on docs: "cookes"

- www/docs.md
This seems to be the actual syntax, `<${variable} />` works fine, but `<#{variable} />` is invalid.
> Fix CSS expression syntax in docs.md

- www/docs.md
Even though the actual code allows for possessive expression or the "it's" contraction for the word "it", let's make the docs grammatically correct.
> Fixed "it's" vs "its" usage to be grammatically correct.

- www/docs.md
It was using the title from previous example
> Fixed wrong title for toggle class on event docs.md

- www/commands/transition.md
In the docs for the transition command there is a contradiction of async commands blocking. This pr "fixes" that.
ps. I know, typo pr-s are lame, but this was confusing.
> Fix transition command docs

- www/commands/render.md
The render command is one of the few exceptions that require the inclusion of an additional script file from the distribution to work. This doc update makes it clearer by mentioning that. as discussed in #496
> update render command documentation to include a note on installation

- src/_hyperscript.js
This was discussed on discord in the context of the following snippet:
```
on change from #id_files
set timestamps to the #id_files.files.lastModified
set #id_timestamp's value to timestamps.join(',')
end
```
It was suggested to just add `FileList` to the "close enough" values for `isArrayLike`, so that we're careful not to accidentally implement iteration over things like `<select>`.
> Add FileList to the bag of 'ArrayLikes'.

- www/features/event-source.md
This just adds a space before the link to WebSockets in the ["Description" section of the eventsource documentation](https://hyperscript.org/features/event-source/#description)
> event-source.md: Add missing space

- src/_hyperscript.js
`Pick match/matches` requires that an identifier be present not the literal token `identifier`
> Fix "pick" command requiring identifier

- src/_hyperscript.js
- test/commands/repeat.js
- www/docs.md
```for item in myList indexed by i```
```for item in myList by i``` Edit: no longer offers this second extra syntax
Support for both of the above index clauses because the normal one reads terribly in a language that otherwise reads amazingly.
The one way to do it before was obviously only
```for item in myList index i```
An example of the new syntax from a project
```
_="
on load put the children of the closest parent <div /> into myList
then for item in myList indexed by i
if the item's index does not exist
set the item's index to i
then set the item's id to item's id + '_' + i
"
```
As opposed to
```
_="
on load put the children of the closest parent <div /> into myList
then for item in myList index i
if the item's index does not exist
set the item's index to i
then set the item's id …
```
> feat(Syntax addition): to match language style, "for item in myList indexed by i"

- www/commands/add.md
- www/expressions/attribute-ref.md
- www/expressions/possessive.md
- www/features/def.md
Some examples were outdated and did not run anymore so I fixed them.
I also added some more examples to make things clearer.
As for the `note` removed from the `add` command's docs, it has been made a non-issue with [release 0.8.4](https://hyperscript.org/posts/2021-11-02-hyperscript-0.8.4-is-released/) by adding a space after the `--` in order to make a comment.
Just a note, on the `add` example, this line does not actually add the color picker's value to the element but the string `my.value`.
I doubled check and I can `log my.value` and got a hex.
I didn't know how to fix it but the example is still important to keep so I just left it :)
Talking about this:
```applescript
on change add { --accent-color: my.value } to document.body
```
> fix(docs): fix and update some examples
