bigskysoftware/_hyperscript

TODO.md, src/_hyperscript.js, test/features/on.js
- like Alpine.js `.away`
- Support both `elsewhere` and `from elsewhere`
- Works with any event
=> Add `elsewhere` modifier to on

src/_hyperscript.js
=> fold `peekToken` functionality into `currentToken`

src/_hyperscript.js, src/worker.js, test/index.html
Worker functionality all lives in worker.js which programmers can choose to include or not.
If a programmer attempts to use workers without including the plugin, they will receive a helpful error message.
=> Extract workers

www/_includes/js_end.md, www/commands/js.md, www/features/js.md, www/features/worker.md
- Workers
- JS docs updated in accordance to changes (function detection)
=> Document some new features

src/lib/core.js, src/lib/web.js, test/expressions/asExpression.js
The "Values" conversion reads all of the input elements within a form (or other DOM node) and populates a {key:value} object with the available names and values.
If this is aimed at a single node, then only its value is returned instead of an object.
=> New Conversion: as Values

src/lib/core.js, src/lib/hdb.js
- Click variable name to log to console
- Eval panel
=> HDB: UI design update & new features

src/lib/core.js, src/lib/types.d.ts, src/lib/types.js
More comments.  
- One tiny code change on line 3864 to include an obviously missing parameter from a public API call.
- Two small syntactically identical code changes on lines 1356 and 1488 to reference custom properties in events more correctly
=> JSDoc: Additional progress

src/lib/hdb.js
We use Shadow DOM so that the HDB panel won't be affected by the host page styling.
=> HDB UI: Style isolation

package-lock.json, src/lib/core.js, src/lib/types.js, test/expressions/comparisonOperator.js, www/docs.md, www/expressions/comparison-operator.md, www/expressions/no.md
This PR addresses #82 -- adding "is empty" and "is not empty" comparison operators to hyperscript.
=> FEATURE: "is empty" and "is not empty"

src/lib/core.js, src/lib/hdb.js
<https://www.youtube.com/watch?v=yorhntABKEU>
=> Make HDB window draggable

src/lib/web.js, test/commands/measure.js, test/index.html
This command can measure:
* bounds
- x
- y
- left
- top
- right
- bottom
- width
- height
* scroll
- scrollLeft
- scrollTop
- scrollLeftMax
- scrollTopMax
- scrollWidth
- scrollHeight
=> `Measure` command

src/lib/core.js
```html
<script type="text/hyperscript">
behavior Draggable
init
add { position: 'absolute' }
end
on pointerdown(pageX, pageY) from <[data-drag-handle]/> in me
preventDefault() on the event
measure my x, y
set xoff to pageX - x
set yoff to pageY - y
trigger draggable:start
repeat until event pointerup from document
wait for pointermove(clientX, clientY)
or pointerup(pageX, pageY) from document
add { left: `${clientX - xoff}px`, top: `${clientY - yoff}px` }
trigger draggable:move
end
trigger draggable:end
end
</script>
<div _="
install Draggable
on draggable:start  put 'Dragging' into .body in me
on draggable:end    put ':)'       into .body in me">
<h2 data-drag-handle>Draggable Window</h2>
<p class="body">:)</p>
</div>
```
=> Behavior & Install

src/lib/core.js, test/commands/append.js, test/index.html
This adds an `append` command to hyperscript that concatenates new values onto the end of a string, array, or HTMLElement's innerHTML.
```hyperscript
append "name" to myString -- adds "name" to the end of the string variable
append "name" to myArray -- .push() "name" as a new value in the array
append "string" to DOMNode -- sets innerHTML
append "string" -- appends value to the default "result" variable 
```
This makes a lot of new operations easy.  This code populates a DIV with a custom widget contents loaded from a remote service.
```hyperscript
def MyWidget(el, records)
append "<table>"
repeat for record in records
append `<tr><td>${record.name}</td><td>${record.value}</td></tr>`
end
append "</table>
put it into me
end
<div script="init fetch /mydata as JSON then call MyWidget(me, …
```
=> FEATURE: Append

www/commands/append.md, www/reference.md
Please let me know if I've left anything out, or if you'd like me to expand on anything else, here.
=> Documentation for "Append" command

src/lib/core.js, src/lib/template.js, test/index.html, test/templates/templates.js
```
<ul>
@repeat for item in items
<li>${item}
@end
</ul>
```
on the right branch this time
=> Add templates

www/_includes/commands_table.md, www/commands/decrement.md, www/commands/increment.md
This PR includes documentation entries for the `increment` and `decrement` commands.
=> DOCS: Increment/Decrement

www/docs.md
- updated to new SSE syntax
- added description of dynamic SSE connections
- small typo error
=> Small docs touchups on SSE

www/posts/2021-04-05-hyperscript-0.0.9-is-released.md
There is a breaking change that we should mention.
=> Add EventSource to release notes

src/lib/core.js, test/features/on.js
=> Remove listeners when the registrant element is removed from the DOM

src/lib/web.js, test/commands/put.js
- Put elements and document fragments
- Putting strings directly into elements will not parse html (breaking)
=> Enhance 'put' command

src/lib/core.js, test/commands/tell.js
as in `on click tell #d2 remove yourself`
with tests
=> Adding "yourself" to resolveSymbols

www/commands/add.md
=> Updated add.md documentation

src/lib/core.js
This is work from @dz4k that is working great on my test code.  We should really merge it into dev so that everyone can use code like: `<script type="text/hyperscript" src=""></script>`
=> FEATURE: Remote Scripts

www/expressions/attribute-ref.md
Update attribute reference expression to new syntax for website
```html
<button _="on click add [disabled='true']">Disable Me!</button>
<button _="on click remove [disabled]">Enable Me!</button>
```
```html
<button _="on click add [@disabled]">Disable Me!</button>
<button _="on click remove [@disabled]">Enable Me!</button>
```
=> Update attribute reference to new syntax

.gitignore, www/docs.md
Completing the twitter->docs lifecycle.
https://twitter.com/htmx_org/status/1400220490699051010?s=12
=> Minor add to docs RE: behavior.

src/lib/core.js, test/expressions/queryRef.js
```hyperscript
<li:not(${me})/>
get the first <${focused} ~ .ring /> then focus() it
```
=> Interpolate elements into query literals

www/css/site.scss, www/index.md
=> Redesign landing page

src/lib/web.js, test/commands/add.js
#151 
<table>
<thead><th>Old<th>New
<tbody><td>
```css
add {
color: 'red',
font-family: `${selectedFont}, sans-serif`
} to me
```
<td>
```css
add {
color: red;
font-family: ${selectedFont}, sans-serif;
} to me
```
</table>
=> Realistic CSS literals

src/lib/eventsource.d.ts, src/lib/eventsource.js, src/lib/types.d.ts, src/lib/types.js
- a few small modifications to type definition comments. No code changes
- all tests passing
=> Additional Comments (type definitions)

www/_includes/layout.njk, www/comparison.md, www/js/prism-hyperscript.js
The examples were changed to be more idiomatic and demonstrate the importance of LoB.
=> Docs: Update Vanilla JS examples in comparison

src/lib/core.js, src/lib/web.js, test/features/behavior.js, test/playground/scratch.html
We weren't establishing a proper scope for evaluating the `from` clause, which lead to me discovering that we didn't have a proper scope for the `init` clause, which lead me to discover that we weren't properly resolving and setting values in the `put` command.
Initial issue:
https://github.com/bigskysoftware/_hyperscript/issues/173
=> scoping fixes

src/lib/core.js, test/commands/if.js
Can it really be this simple??
=> Add `otherwise` as an alias for `else`

www/features/on.md
Just added one character. That's my very first pull request (with the help of https://www.dataschool.io/how-to-contribute-on-github/ , by the way), so I am quite nervous now …
=> minor typo

src/lib/core.js, test/expressions/queryRef.js
Another change to ElementCollection
=> Fix 211: Only escape class literals

src/lib/core.js, test/expressions/comparisonOperator.js, test/expressions/no.js
This is a fix for https://github.com/bigskysoftware/_hyperscript/issues/209
I think it needs to be implemented for TemplatedQueryElementCollection as well.  @dz4k, thoughts?
=> Fix 209: ElementCollection breaks some comparison functionality

www/docs.md
This adds an example that demonstrates the ability to put the event handlers on the counter itself, having it listen and react to click events on each of the buttons.
=> Add example of putting event handlers on counter

www/features/behavior.md
- Added script tags to behavior definitions, as it was previously how/where to put them
- Added notes on ordering
=> Updated behavior feature

src/lib/plugin/template.js
was using templates and noticed a ton of output
=> remove console.log

www/_includes/layout.njk
=> Added sorely needed basic global search.

www/cookbook/40-disable-btn-during-request.md
Change `toggle [disabled='true']` to `toggle @disabled`.
Love the project!
=> Change to use `toggle @disabled`

www/docs.md
..... or remove the requirement for whitespace?
=> clarify that a whitespace is needed

www/cookbook/70-drag-n-drop.md
=> cookbook: initial drag and drop demo

www/commands/pseudo-commands.md, www/reference.md
=> Document naming caveat for pseudo-commands

www/docs.md
Small fix to the menu tower on Desktop.
Leaves mobile alone. 
While we wait for something more significant to be done here...
Before
After
=> Docs: Fix bad experience specifically on Desktop

www/docs.md
=> Docs: New comment types.

www/commands/async.md, www/commands/break.md, www/commands/decrement.md, www/commands/fetch.md, www/commands/halt.md, www/commands/js.md, www/commands/send.md, www/commands/transition.md, www/commands/wait.md, www/docs.md, www/features/behavior.md, www/features/def.md, www/features/event-source.md
First of all: _hyperscript looks brilliant!
As I am not yet familiar with its code base, I thought it may be better to start my contributions by providing a few minimal changes of the docs first (just typos that have been fixed)
With greetings from Germany,
Andreas Rozek
=> just a few typo fixes

www/commands/send.md
Fixes #388 for reasons stated there.
=> Fix #388 - `trigger x on y` conflicts with `on event` syntax

www/docs.md
- add explanation for unless modifier with example
- fix typo for css pseudo class :focus
=> add explanation for unless modifier

www/expressions.md
I struggled for a while trying to figure out how to toggle properties of `:root` using hyperscript. I thought this might be useful.
=> Add note about querying for the :root pseudo-element

www/docs.md
Added install instruction for use with a build step.
Inspired by https://github.com/bigskysoftware/_hyperscript/issues/494#issuecomment-1815276274, removed some of the code that I don't think is strictly necessary.
=> Add install docs for those using a build step

www/docs.md, www/reference.md
This PR fixes some broken links in the docs and reference.
=> Docs: Fixes broken links

src/_hyperscript.js, test/core/tokenizer.js
addresses https://github.com/bigskysoftware/_hyperscript/issues/561
=> fix(templates): fixed string interpolation in template strings

www/docs.md
Update docs.md
- fix token to matchToken in Extending on line 2223
- tested the code it works now else it threw error: " tokens.match is not a function "
=> token should be matchToken

www/commands/hide.md
Added the safe listing for tailwind v4.0.
=> Added the safe listing for tailwind v4.0.
